spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/dbi5b4m0bd39ks
    username: smrafoywscldkx
    password: bec7b51ea9aab1b78a9821f70cb4295d92711050230ccfbc7bd9fba01a62ed61
    driverClassName: org.postgresql.Driver
  flyway:
    locations: db/migration

server:
  error:
    include-binding-errors: always
    include-message: always



